apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - ../../base

namePrefix: prod-

patches:
  - target:
      kind: ConfigMap
      name: app-config
    patch: |-
      - op: replace
        path: /data/NODE_ENV
        value: production
      - op: replace
        path: /data/LOG_LEVEL
        value: warn
      - op: replace
        path: /data/REDIS_HOST
        value: prod-redis-service
      - op: replace
        path: /data/MONGODB_URI
        value: mongodb://prod-mongodb-service:27017/ai-task-platform
      - op: replace
        path: /data/FRONTEND_URL
        value: http://prod-frontend-service
  - target:
      kind: Deployment
      name: worker
    patch: |-
      - op: replace
        path: /spec/replicas
        value: 3
  - target:
      kind: Deployment
      name: backend
    patch: |-
      - op: replace
        path: /spec/replicas
        value: 3
  - target:
      kind: Deployment
      name: frontend
    patch: |-
      - op: replace
        path: /spec/replicas
        value: 3
