apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - ../../base

namePrefix: dev-

patches:
  - target:
      kind: ConfigMap
      name: app-config
    patch: |-
      - op: replace
        path: /data/NODE_ENV
        value: development
      - op: replace
        path: /data/LOG_LEVEL
        value: debug
      - op: replace
        path: /data/REDIS_HOST
        value: dev-redis-service
      - op: replace
        path: /data/MONGODB_URI
        value: mongodb://dev-mongodb-service:27017/ai-task-platform
      - op: replace
        path: /data/FRONTEND_URL
        value: http://dev-frontend-service
  - target:
      kind: Deployment
      name: worker
    patch: |-
      - op: replace
        path: /spec/replicas
        value: 1
  - target:
      kind: Deployment
      name: backend
    patch: |-
      - op: replace
        path: /spec/replicas
        value: 1
  - target:
      kind: Deployment
      name: frontend
    patch: |-
      - op: replace
        path: /spec/replicas
        value: 1
